import { db, Publication } from 'astro:db';

// https://astro.build/db/seed
export default async function seed() {
  await db.insert(Publication).values([
		{
			pubID: 1,
			title: "Healthy Families New York: A Home Visiting Program that Works 2012",
			category: "Fact Sheet",
			fullPath: "http://www.ocfs.state.ny.us/main/publications/Pub5134.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 2,
			title: "Early Program Cost Synopsis: 2009",
			category: "Fact Sheet",
			fullPath: "../Media/pdf/HFNY_Program_Cost_Synopsis_12-14-09.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 3,
			title: "Healthy Families New York:Status Report - 2021",
			category: "Status Report",
			fullPath: "Publications/PreventionStatus2020HFNY05.2021.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 4,
			title: "Community Based Prevention Programs:Status Report - April 2021",
			category: "Status Report",
			fullPath: "/media/pdf/PreventionStatus042021.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 5,
			title: "Community Based Prevention Programs:Status Report - March 2021",
			category: "Status Report",
			fullPath: "Publications/PreventionStatusReport032021.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 6,
			title: "Community Based Prevention Programs:Status Report - February 2021",
			category: "Status Report",
			fullPath: "Publications/PreventionStatus2021February.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 7,
			title: "Community Based Prevention Programs:Status Report - January 2021",
			category: "Status Report",
			fullPath: "Publications/PreventionStatus2021_january.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 8,
			title: "Community Based Prevention Programs:Status Report - December - 2020",
			category: "Status Report",
			fullPath: "Publications/PreventionStatus2020_December.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID:9,
			title: "Community Based Prevention Programs:Status Report - November - 2020",
			category: "Status Report",
			fullPath: "Publications/preventionstatus112020.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 10,
			title: "Community Based Prevention Programs:Status Report - October - 2020",
			category: "Status Report",
			fullPath: "Publications/PreventionStatusReport2020October.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 11,
			title: "Community Based Prevention Programs:Status Report - September - 2020",
			category: "Status Report",
			fullPath: "Publications/PreventionStatusReport2020September.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 12,
			title: "Community Based Prevention Programs:Status Report - August - 2020",
			category: "Status Report",
			fullPath: "/Media/pdf/HFNYPreventionStatus.August2020.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 13,
			title: "Community Based Prevention Programs:Status Report - July - 2020",
			category: "Status Report",
			fullPath: "Publications/PreventionStatus.July2020.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 14,
			title: "Community Based Prevention Programs:Status Report - June - 2020",
			category: "Status Report",
			fullPath: "/Staff/Documents/Prevention_Status_June2020.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 15,
			title: "Community Based Prevention Programs:Status Report - May 2020",
			category: "Status Report",
			fullPath: "/Staff/Documents/Prevention_Status_May.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 16,
			title: "Community Based Prevention Programs:Status Report - April 2020",
			category: "Status Report",
			fullPath: "Publications/Prevention Status-April FINAL.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 17,
			title: "Shifting Patterns in Healthy Families New York Referrals - 2024",
			category: "Research Brief",
			fullPath: "Publications/Shifting Patterns in HFNY Referrals 2024_approved.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 18,
			title: "Research Brief - Changes in Assessment scores after Implementation of One-Step Process Pilot 2015-2020",
			category: "Research Brief",
			fullPath: "/Staff/Documents/Research Brief - Changes in Assessment scores after Implementation of One-Step Process Pilot 2015-2020_final.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 19,
			title: "Healthy Families New York: Findings from a Pilot Study of nrollment Processes - 03/2021",
			category: "Research Brief",
			fullPath: "/Staff/Documents/HFNY_CE_ResearchBriefY1Final.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 20,
			title: "Research Brief Fall 2019, Curricula Delivery at Healthy Families New York Programs",
			category: "Research Brief",
			fullPath: "/Staff/Documents/CurriculaDeliveryHF2019dated2019_11_20_final.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 21,
			title: "Social Network Analysis of HFNY Referrals",
			category: "Research Brief",
			fullPath: "Publications/SocialNetworkAnalysisBrief2019.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 22,
			title: "Exploring Strengths and Challenges in Obtaining Referrals from the Women, Infants and Children Program",
			category: "Research Brief",
			fullPath: "Publications/WICPosterResults8.15.19FinalforWebsite.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 23,
			title: "Key Demographic and Organizational Factors in Predicting Healthy Families New York Home Visitor Retention",
			category: "Research Brief",
			fullPath: "..\Media\pdf\HFNYResearchBriefSummer2018.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 24,
			title: "Healthy Families New York Prevents Child Maltreatment 2013",
			category: "Research Brief",
			fullPath: "Publications/HFNYPreventsChildMaltreatment09-2013.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 25,
			title: "Healthy Families New York Home Visiting Program Improves Birth Outcomes &mdash; Research Brief",
			category: "Research Brief",
			fullPath: "Publications/LBW_Research_Brief.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 26,
			title: "Healthy Families New York Promotes Success at School 2012",
			category: "Research Brief",
			fullPath: "Publications/HFNYPromotesSuccessatSchoolwithcitation.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 27,
			title: "The Healthy Families New York Home Visiting Program: Findings from the Randomized Controlled Trial, 2010",
			category: "Research Brief",
			fullPath: "http://www.ocfs.state.ny.us/main/reports/Healthy%20Families%20New%20York%20Short%2011-24-2010%20FINAL.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 28,
			title: "Healthy Families New York: Results of First Year Evaluation, 2004",
			category: "Research Brief",
			fullPath: "Publications/HFNY-First-Year-Evaluation.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 29,
			title: "HFNY Annual Report - 2022-2023",
			category: "Report",
			fullPath: "/Media/pdf/HFNY-Annual-Report-2022-2023.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 30,
			title: "2019 HFNY Triennial Report",
			category: "Report",
			fullPath: "Publications/2019HFNYTriennialReport102020.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 31,
			title: "2018-2019 HFNY Annual Service Review - Appendix C",
			category: "Report",
			fullPath: "/Media/pdf/2018_2019HFNYAnnualServiceReview9.17.20_Appendix C.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 32,
			title: "2017-2018 HFNY Annual Service Review - Appendix B",
			category: "Report",
			fullPath: "/Media/pdf/2017_2018HFNYAnnualServiceReview_Appendix B.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 33,
			title: "Healthy Families New York Home Visiting Program: 2016 Triennial Report",
			category: "Report",
			fullPath: "Publications/2016triennialhfnyreport.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 34,
			title: "HEALTHY FAMILIES NEW YORK: PROGRAM SERVICES AND OUTCOMES ANALYSIS 2016 - 2017",
			category: "Report",
			fullPath: "Publications/HFNY2016.2017ProgramServicesandOutcomesAnalysisReport092020.pdf",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 35,
			title: "Evaluating the effectiveness of home visiting services in promoting children&rsquo;s adjustment in school: Final report to the Pew Center on the States.",
			category: "Report",
			fullPath: "Publications/EvaluatingEffectivenessofHomeVisitingServicesinPromotingChildrensAjustmenttoSchool.pdf",
			additionalInfo: "Kirkland, K. &amp; Mitchell-Herzfeld, S. (2012). Rensselaer, New York: New York State Office of Children and Family Services.",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 36,
			title: "A randomized trial of Healthy Families New York (HFNY): Does home visiting prevent child maltreatment?",
			category: "Report",
			fullPath: "https://www.ncjrs.gov/pdffiles1/nij/grants/232945.pdf",
			additionalInfo: "DuMont, K., Kirkland, K., Mitchell-Herzfeld, S., Ehrhard-Dietzel, S., Rodriquez, M., Lee, E., Layne, C., and Greene, R. (2011). Final Report to National Institute of Justice (Grant # 2006-MU-MU-0002).",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 37,
			title: "Effects of Healthy Families New York on maternal behaviors: Observational assessments of positive and negative parenting",
			category: "Report",
			fullPath: "Publications/final_HFNY_obs_working_paper_7-16-08.pdf",
			additionalInfo: "DuMont, K., Rodriguez, M., Mitchell-Herzfeld, S., Walden, N., Kirkland, K., Greene, R., & Lee, E. (2008). Rensselaer, NY: New York State Office of Children and Family Services.",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 38,
			title: "Healthy Families New York (HFNY) randomized trial: Impacts on parenting after the first two years.",
			category: "Report",
			fullPath: "Publications/HFNYRandomizedTrialWorkingPaper.pdf",
			additionalInfo: "DuMont, K., Mitchell-Herzfeld, S., Greene, R., Lee, E., Lowenfels, A., & Rodriquez, M. (2006). Rensselaer, NY: New York State Office of Children & Family Services.",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 39,
			title: "Evaluation of Healthy Families New York (HFNY): First year program impacts",
			category: "Report",
			fullPath: "Publications/HFNYEvalReport.pdf",
			additionalInfo: "Mitchell-Herzfeld, S., Izzo, C., Greene, R., Lee, E. & Lowenfels, A. (2005). Rensselaer, NY: New York State Office of Children & Family Services.",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 40,
			title: "Sustained Impact on Parenting Practices: Year 7 Findings from the Healthy Families New York Randomized Controlled Trial",
			category: "Journal",
			fullPath: "https://link.springer.com/article/10.1007/s11121-020-01110-w",
			additionalInfo: "Kristen Kirkland,Eunju Lee, Carolyn Smith, and Rose Greene - Prevention Science volume 21,pages 498–507(2020)",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 41,
			title: "Reducing Maltreatment Recurrence Through Home Visitation: A Promising Intervention for Child Welfare Involved Families",
			category: "Journal",
			fullPath: "/Media/pdf/2018reducingmaltreatmentthroughhv.pdf",
			additionalInfo: "Eunju Lee, Kristen Kirkland, Claudia Miranda-Julian, and Rose Greene - Child Abuse &amp; Neglect: The International Journal, Volume 86, Dec. 2018",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 42,
			title: "Engaging At-Risk Fathers in Home Visiting Services: Effects on Program Retention and Father Involvement",
			category: "Journal",
			fullPath: "..\Media\pdf\Engaging At-Risk Fathers in Home Visiting Services_ Effects on Program Retention and Father Involvement.pdf",
			additionalInfo: "Sandra McGinnis, Eunju Lee, Kristen Kirkland, Carolyn Smith, Claudia Miranda-Julian and Rose Greene - Child and Adolescent Social Work Journal, July 2018",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 43,
			title: "Let's Talk About Breastfeeding: The Importance of Delivering a Message in a Home Visiting Program",
			category: "Journal",
			fullPath: "Publications/HFNYBFSMpper.pdf",
			additionalInfo: "Sandra McGinnis, Eunju Lee, Kristen Kirkland,Claudia Miranda-Julian, and Rose Greene (2017) American Journal of Health Promotion 1-8",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 44,
			title: "Effectiveness of home visiting as a strategy for promoting children&rsquo;s adjustment to school.",
			category: "Journal",
			fullPath: "https://zerotothree.sharepoint.com/sites/Communications/ExternalResources/_layouts/15/guestaccess.aspx?guestaccesstoken=JaH%2fA0qDNnLBcS3kKhUhCE2DP0CTkLGdL6sWETS69lI%3d&docid=1d4b824f13d2f4f7093b2c70d6737646a",
			additionalInfo: "Kirkland, K. (2013). Zero to Three, 33, 31-37.",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 45,
			title: "Organizational climate and burnout among home visitors: Testing mediating effects of empowerment.",
			category: "Journal",
			fullPath: "http://www.sciencedirect.com/science/article/pii/S0190740913000406",
			additionalInfo: "Lee, E., Esaki, N., Kim, J., Greene, R., Kirkland, K. & Mitchell-Herzfeld, S. (2013). Children and Youth Services Review, 35, 594-602.",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 46,
			title: "Averting child maltreatment: Individual, social, and community resources.",
			category: "Journal",
			fullPath: "http://link.springer.com/chapter/10.1007%2F978-1-4614-0586-3_17",
			additionalInfo: "DuMont, K., Ehrhard-Dietzel, S. & Kirkland, K. (2011) in Michael Ungar (Ed.) The Social Ecology of Resilience: A Handbook of Theory and Practice.",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 47,
			title: "Risk and protective factors for child neglect during early childhood: A cross-study comparison.",
			category: "Journal",
			fullPath: "http://www.sciencedirect.com/science/article/pii/S0190740911001460",
			additionalInfo: "Shook-Slack, K., Berger, L. M., DuMont, K., Yang. M., Kim, B., Ehrhard-Dietzel, S. & Holl, J. L. (2011) Children and Youth Services Review, 33, 1354-1363.",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 48,
			title: "Effects of Healthy Families New York on the promotion of maternal parenting competencies and the prevention of harsh parenting.",
			category: "Journal",
			fullPath: "http://www.sciencedirect.com/science/article/pii/S0145213410002164",
			additionalInfo: "Rodriguez, M. L., Dumont, K., Mitchell-Herzfeld, S. D., Walden, N. J., Greene, R. (2010). Child Abuse and Neglect, 34, 711-723.",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 49,
			title: "Reducing low birth weight through home visitation: A randomized controlled trial.",
			category: "Journal",
			fullPath: "Publications/HFNY_low_birth_weight_article.pdf",
			additionalInfo: "Lee, E., Mitchell-Herzfeld, S., Lowenfels, A., Greene, R., Dorabawila, V., & DuMont, K. (2009). American Journal of Preventive Medicine, 36, 154-160.",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 50,
			title: "Author response: Reducing low birth weight through home visitation.",
			category: "Journal",
			fullPath: "http://www.sciencedirect.com/science/article/pii/S074937970900511X",
			additionalInfo: "Lee, E., Greene, R., Mitchell-Herzfeld, S., & DuMont, K. (2009). American Journal of Preventive Medicine, 37, 472-473.",
			dateAdded: new Date("2025-03-17"),
		},
		{
			pubID: 51,
			title: "Healthy Families New York (HFNY) randomized trial: Effects on early child abuse and neglect.",
			category: "Journal",
			fullPath: "http://www.sciencedirect.com/science/article/pii/S0145213408000148",
			additionalInfo: "DuMont, K., Mitchell-Herzfeld, S., Greene, R., Lee, E., Lowenfels, A., Rodriguez, M., & Dorabawila, V. (2008). Child Abuse & Neglect, 32, 295-315.",
			dateAdded: new Date("2025-03-17"),
		},
  ]);
}
